# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import services_pb2 as services__pb2


class WatermarkServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.addImageWatermark = channel.unary_unary(
            "/WatermarkService/addImageWatermark",
            request_serializer=services__pb2.Request.SerializeToString,
            response_deserializer=services__pb2.Image.FromString,
        )


class WatermarkServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def addImageWatermark(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_WatermarkServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "addImageWatermark": grpc.unary_unary_rpc_method_handler(
            servicer.addImageWatermark,
            request_deserializer=services__pb2.Request.FromString,
            response_serializer=services__pb2.Image.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "WatermarkService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class WatermarkService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def addImageWatermark(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/WatermarkService/addImageWatermark",
            services__pb2.Request.SerializeToString,
            services__pb2.Image.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
